INSERT INTO products (product_name, size, unit, category_id) VALUES ('Whole Chicken', 1.65, 'kg', 12);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Free Range Chicken Breast', 1.25, 'kg', 12);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Turkey Breast Roast', 1, 'kg', 1);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Beef T Bone Steak', 0.5, 'kg', 14);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Beef Porterhouse Steak', 0.5, 'kg', 14);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Lamb Loin Chops', 0.9, 'kg', 11);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Lamb Leg Roast Half', 1.75, 'kg', 11);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Pork Loin Chops', 0.9, 'kg', 15);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Point Cutlets', 0.5, 'kg', 1);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Tasmanian Smoked Salmon', 0.25, 'kg', 13);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Thawed Australian Cooked Black Tiger Prawns', 0.25, 'kg', 13);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Australian Barramundi Portions', 0.26, 'kg', 13);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Pink Lady Apples', 0.16, 'kg', 16);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Hass Avocados', 1, 'kg', 2);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Organic Bananas', 0.18, 'kg', 16);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Carrots', 0.17, 'kg', 17);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('White Seedless Grapes Loose', 0.8, 'kg', 16);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Iceberg Lettuce', 1, 'each', 17);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Kensington Pride Mangoes', 1, 'each', 16);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Fresh Loose Cup Mushrooms', 0.2, 'kg', 2);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Medium Navel Oranges', 0.18, 'kg', 16);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Red Royale Potatoes', 0.17, 'kg', 2);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Strawberries', 0.25, 'kg', 16);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Truss Tomatoes', 0.14, 'kg', 17);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Full Cream Milk', 2, 'L', 8);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Skim Milk', 2, 'L', 8);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Lactose Free Light Milk', 2, 'L', 8);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Regular Soy Milk', 1, 'L', 8);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Eggs Free Range 12 Pack', 0.7, 'kg', 10);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Cage Free Large Eggs 18 pack', 0.9, 'kg', 10);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Tasty Cheese Slices 24 Pack', 0.5, 'kg', 9);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Vintage Cheddar', 0.14, 'kg', 9);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Greek Style Natural Yoghurt', 1, 'kg', 3);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Thick & Creamy Classic Vanilla Yoghurt', 0.15, 'kg', 3);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('White Bread', 0.65, 'kg', 4);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Light Rye Bread', 0.68, 'kg', 4);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('High Fibre Multigrain Bread', 0.7, 'kg', 4);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Gluten Free Farmhouse Soft Brown Bread Loaf', 0.535, 'kg', 4);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Sourdough Bread', 0.65, 'kg', 4);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Heinz Baked Beans', 0.555, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Sweet Chilli & Sour Cream Potato Chips', 0.29, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Original BBQ Shapes', 0.175, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Original Chocolate Tim Tam', 0.2, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Espresso Coffee Beans', 1, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Kit Kat Dark Chocolate Block', 0.17, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Minties', 0.15, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('nutri-Grain Protein Breakfast Cereal', 0.765, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Weet Bix', 0.375, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Tomato Sauce', 0.3, 'L', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Crunchy Peanut Butter', 0.375, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Cottees Jam Strawberry Conserve', 0.5, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('English Breakfast Tea Bags 100 pack', 0.2, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Pure Green Tea Bags 100 pack', 0.15, 'kg', 5);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Cola Cola Classic', 1.25, 'L', 6);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Schweppes Lemonade', 1.1, 'L', 6);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Red Bull Energy Drink (4*250ml)', 4, 'pack', 6);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Gatorade Lemon & Lime Sports Drink', 0.6, 'L', 6);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Colgate Total Original Antibacterial Toothpaste', 0.2, 'kg', 7);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Oral-B Pro-Health Advanced All Around Protection', 0.11, 'kg', 7);
INSERT INTO products (product_name, size, unit, category_id) VALUES ('Head & Shoulders Clean & Balanced Shampoo', 0.85, 'L', 7);