version: '3.4'
services:
  api:
    platform: "linux/amd64"
    build: backend/products
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://database:3306/teamDB?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: root
      spring.datasource.password: password
    depends_on:
      - database
  web:
    platform: "linux/amd64"
    build: frontend/comparison-shopper/
    ports:
      - "3000:3000"
    environment:
      API_URL: "http://api:8080"
    depends_on:
      - api

  database:
    platform: "linux/amd64"
    image: mysql:8.0-oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: teamDB
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  adminer:
    platform: "linux/amd64"
    image: adminer
    restart: always
    ports:
      - 9000:8080

volumes:
  db:
  
